version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./front-react
    volumes:
      - /usr/src/front/node_modules
      - ./front-react:/usr/src/front
    stdin_open: true
    networks:
      - app_net

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx-proxy
    ports: 
      - "3000:80"
    networks:
      - app_net

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./back-node
    container_name: app_backend
    volumes:
      - /usr/src/back/node_modules
      - ./back-node:/usr/src/back
    environment:
      MYSQL_ROOT_PASSWORD: dkansk123
      MYSQL_DATABASE: web
      MYSQL_HOST: 172.19.16.1
      MYSQL_USER: zerogon
      MYSQL_PORT: 3306
    networks: 
      - app_net
      - mysql_net

networks:
  app_net:
  mysql_net:
    external: true